# config.yaml  (place at repo root)
data:
  paths:
    - data/I09_3.csv
  independent_test_path: data/test.csv        # relative or absolute
  response: response        # name of target column

pipeline:
  algorithm: svm          # algorithm name (svm, rf, xgb, cart)
  feature_selection: anova  # feature selection (anova, lasso, mutual_info)
  use_outlier_detection: false
  output_folder: results/

    # --- outlier-detection config ----------------
  use_outlier_detection: false           # true / false
  outlier_method: pca                   # iqr | zscore | isolation_forest | pca 
  iqr_threshold: 0.05                   # pca works
  zscore_threshold: 0.05
  zscore_limit: 3.0
  iso_forest_threshold: 0.05
  pca_reconstruction_error_threshold: 0.3
  n_components_pca: 3                # null -> auto
  explain: none      # none | shap 
  run_extra_analysis: false  # disables all report generation & plots

cv:
  random_seeds: [42, 43, 44, 45, 46]
